import React from "react";

export default function Loading() {
  return (
    <div style={{ textAlign: "center", marginTop: "200px" }}>
      <div>
        <div className="loadingio-spinner-double-ring-4q0lj114yu">
          <div className="ldio-1fsmxxej381">
            <div />
            <div />
            <div>
              <div />
            </div>
            <div>
              <div />
            </div>
          </div>
        </div>
        <style
          type="text/css"
          dangerouslySetInnerHTML={{
            __html:
              '\n@keyframes ldio-1fsmxxej381 {\n  0% { transform: rotate(0) }\n  100% { transform: rotate(360deg) }\n}\n.ldio-1fsmxxej381 div { box-sizing: border-box!important }\n.ldio-1fsmxxej381 > div {\n  position: absolute;\n  width: 222.5px;\n  height: 222.5px;\n  top: 13.75px;\n  left: 13.75px;\n  border-radius: 50%;\n  border: 22.5px solid #000;\n  border-color: #1976d2 transparent #1976d2 transparent;\n  animation: ldio-1fsmxxej381 1s linear infinite;\n}\n\n.ldio-1fsmxxej381 > div:nth-child(2), .ldio-1fsmxxej381 > div:nth-child(4) {\n  width: 172.5px;\n  height: 172.5px;\n  top: 38.75px;\n  left: 38.75px;\n  animation: ldio-1fsmxxej381 1s linear infinite reverse;\n}\n.ldio-1fsmxxej381 > div:nth-child(2) {\n  border-color: transparent #f8d06a transparent #f8d06a\n}\n.ldio-1fsmxxej381 > div:nth-child(3) { border-color: transparent }\n.ldio-1fsmxxej381 > div:nth-child(3) div {\n  position: absolute;\n  width: 100%;\n  height: 100%;\n  transform: rotate(45deg);\n}\n.ldio-1fsmxxej381 > div:nth-child(3) div:before, .ldio-1fsmxxej381 > div:nth-child(3) div:after { \n  content: "";\n  display: block;\n  position: absolute;\n  width: 22.5px;\n  height: 22.5px;\n  top: -22.5px;\n  left: 77.5px;\n  background: #1976d2;\n  border-radius: 50%;\n  box-shadow: 0 200px 0 0 #1976d2;\n}\n.ldio-1fsmxxej381 > div:nth-child(3) div:after {\n  left: -22.5px;\n  top: 77.5px;\n  box-shadow: 200px 0 0 0 #1976d2;\n}\n\n.ldio-1fsmxxej381 > div:nth-child(4) { border-color: transparent; }\n.ldio-1fsmxxej381 > div:nth-child(4) div {\n  position: absolute;\n  width: 100%;\n  height: 100%;\n  transform: rotate(45deg);\n}\n.ldio-1fsmxxej381 > div:nth-child(4) div:before, .ldio-1fsmxxej381 > div:nth-child(4) div:after {\n  content: "";\n  display: block;\n  position: absolute;\n  width: 22.5px;\n  height: 22.5px;\n  top: -22.5px;\n  left: 52.5px;\n  background: #f8d06a;\n  border-radius: 50%;\n  box-shadow: 0 150px 0 0 #f8d06a;\n}\n.ldio-1fsmxxej381 > div:nth-child(4) div:after {\n  left: -22.5px;\n  top: 52.5px;\n  box-shadow: 150px 0 0 0 #f8d06a;\n}\n.loadingio-spinner-double-ring-4q0lj114yu {\n  width: 250px;\n  height: 250px;\n  display: inline-block;\n  overflow: hidden;\n  background: #ffffff;\n}\n.ldio-1fsmxxej381 {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-1fsmxxej381 div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n',
          }}
        />
      </div>
    </div>
  );
}
